/*
 * Pulp 3 API
 *
 * Fetch, Upload, Organize, and Distribute Software Packages
 *
 * API version: v3
 * Contact: pulp-list@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DebVerbatimPublication A Serializer for VerbatimPublication.
type DebVerbatimPublication struct {
	RepositoryVersion *string `json:"repository_version,omitempty"`
	// A URI of the repository to be published.
	Repository *string `json:"repository,omitempty"`
}

// NewDebVerbatimPublication instantiates a new DebVerbatimPublication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebVerbatimPublication() *DebVerbatimPublication {
	this := DebVerbatimPublication{}
	return &this
}

// NewDebVerbatimPublicationWithDefaults instantiates a new DebVerbatimPublication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebVerbatimPublicationWithDefaults() *DebVerbatimPublication {
	this := DebVerbatimPublication{}
	return &this
}

// GetRepositoryVersion returns the RepositoryVersion field value if set, zero value otherwise.
func (o *DebVerbatimPublication) GetRepositoryVersion() string {
	if o == nil || o.RepositoryVersion == nil {
		var ret string
		return ret
	}
	return *o.RepositoryVersion
}

// GetRepositoryVersionOk returns a tuple with the RepositoryVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebVerbatimPublication) GetRepositoryVersionOk() (*string, bool) {
	if o == nil || o.RepositoryVersion == nil {
		return nil, false
	}
	return o.RepositoryVersion, true
}

// HasRepositoryVersion returns a boolean if a field has been set.
func (o *DebVerbatimPublication) HasRepositoryVersion() bool {
	if o != nil && o.RepositoryVersion != nil {
		return true
	}

	return false
}

// SetRepositoryVersion gets a reference to the given string and assigns it to the RepositoryVersion field.
func (o *DebVerbatimPublication) SetRepositoryVersion(v string) {
	o.RepositoryVersion = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *DebVerbatimPublication) GetRepository() string {
	if o == nil || o.Repository == nil {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebVerbatimPublication) GetRepositoryOk() (*string, bool) {
	if o == nil || o.Repository == nil {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *DebVerbatimPublication) HasRepository() bool {
	if o != nil && o.Repository != nil {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *DebVerbatimPublication) SetRepository(v string) {
	o.Repository = &v
}

func (o DebVerbatimPublication) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RepositoryVersion != nil {
		toSerialize["repository_version"] = o.RepositoryVersion
	}
	if o.Repository != nil {
		toSerialize["repository"] = o.Repository
	}
	return json.Marshal(toSerialize)
}

type NullableDebVerbatimPublication struct {
	value *DebVerbatimPublication
	isSet bool
}

func (v NullableDebVerbatimPublication) Get() *DebVerbatimPublication {
	return v.value
}

func (v *NullableDebVerbatimPublication) Set(val *DebVerbatimPublication) {
	v.value = val
	v.isSet = true
}

func (v NullableDebVerbatimPublication) IsSet() bool {
	return v.isSet
}

func (v *NullableDebVerbatimPublication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebVerbatimPublication(val *DebVerbatimPublication) *NullableDebVerbatimPublication {
	return &NullableDebVerbatimPublication{value: val, isSet: true}
}

func (v NullableDebVerbatimPublication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebVerbatimPublication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


