/*
 * Pulp 3 API
 *
 * Fetch, Upload, Organize, and Distribute Software Packages
 *
 * API version: v3
 * Contact: pulp-list@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// DebBasePackageResponse A Serializer for InstallerPackage.
type DebBasePackageResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Artifact file representing the physical content
	Artifact *string `json:"artifact,omitempty"`
	// Path where the artifact is located relative to distributions base_path
	RelativePath *string `json:"relative_path,omitempty"`
	// The MD5 checksum if available.
	Md5 *string `json:"md5,omitempty"`
	// The SHA-1 checksum if available.
	Sha1 *string `json:"sha1,omitempty"`
	// The SHA-224 checksum if available.
	Sha224 *string `json:"sha224,omitempty"`
	// The SHA-256 checksum if available.
	Sha256 *string `json:"sha256,omitempty"`
	// The SHA-384 checksum if available.
	Sha384 *string `json:"sha384,omitempty"`
	// The SHA-512 checksum if available.
	Sha512 *string `json:"sha512,omitempty"`
	Package *string `json:"package,omitempty"`
	Source *string `json:"source,omitempty"`
	Version *string `json:"version,omitempty"`
	Architecture *string `json:"architecture,omitempty"`
	Section *string `json:"section,omitempty"`
	Priority *string `json:"priority,omitempty"`
	Origin *string `json:"origin,omitempty"`
	Tag *string `json:"tag,omitempty"`
	Bugs *string `json:"bugs,omitempty"`
	Essential *string `json:"essential,omitempty"`
	BuildEssential *string `json:"build_essential,omitempty"`
	InstalledSize *string `json:"installed_size,omitempty"`
	Maintainer *string `json:"maintainer,omitempty"`
	OriginalMaintainer *string `json:"original_maintainer,omitempty"`
	Description *string `json:"description,omitempty"`
	DescriptionMd5 *string `json:"description_md5,omitempty"`
	Homepage *string `json:"homepage,omitempty"`
	BuiltUsing *string `json:"built_using,omitempty"`
	AutoBuiltPackage *string `json:"auto_built_package,omitempty"`
	MultiArch *string `json:"multi_arch,omitempty"`
	Breaks *string `json:"breaks,omitempty"`
	Conflicts *string `json:"conflicts,omitempty"`
	Depends *string `json:"depends,omitempty"`
	Recommends *string `json:"recommends,omitempty"`
	Suggests *string `json:"suggests,omitempty"`
	Enhances *string `json:"enhances,omitempty"`
	PreDepends *string `json:"pre_depends,omitempty"`
	Provides *string `json:"provides,omitempty"`
	Replaces *string `json:"replaces,omitempty"`
}

// NewDebBasePackageResponse instantiates a new DebBasePackageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebBasePackageResponse() *DebBasePackageResponse {
	this := DebBasePackageResponse{}
	return &this
}

// NewDebBasePackageResponseWithDefaults instantiates a new DebBasePackageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebBasePackageResponseWithDefaults() *DebBasePackageResponse {
	this := DebBasePackageResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetPulpHref() string {
	if o == nil || o.PulpHref == nil {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || o.PulpHref == nil {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasPulpHref() bool {
	if o != nil && o.PulpHref != nil {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *DebBasePackageResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetPulpCreated() time.Time {
	if o == nil || o.PulpCreated == nil {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || o.PulpCreated == nil {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasPulpCreated() bool {
	if o != nil && o.PulpCreated != nil {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *DebBasePackageResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetArtifact returns the Artifact field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetArtifact() string {
	if o == nil || o.Artifact == nil {
		var ret string
		return ret
	}
	return *o.Artifact
}

// GetArtifactOk returns a tuple with the Artifact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetArtifactOk() (*string, bool) {
	if o == nil || o.Artifact == nil {
		return nil, false
	}
	return o.Artifact, true
}

// HasArtifact returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasArtifact() bool {
	if o != nil && o.Artifact != nil {
		return true
	}

	return false
}

// SetArtifact gets a reference to the given string and assigns it to the Artifact field.
func (o *DebBasePackageResponse) SetArtifact(v string) {
	o.Artifact = &v
}

// GetRelativePath returns the RelativePath field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetRelativePath() string {
	if o == nil || o.RelativePath == nil {
		var ret string
		return ret
	}
	return *o.RelativePath
}

// GetRelativePathOk returns a tuple with the RelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetRelativePathOk() (*string, bool) {
	if o == nil || o.RelativePath == nil {
		return nil, false
	}
	return o.RelativePath, true
}

// HasRelativePath returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasRelativePath() bool {
	if o != nil && o.RelativePath != nil {
		return true
	}

	return false
}

// SetRelativePath gets a reference to the given string and assigns it to the RelativePath field.
func (o *DebBasePackageResponse) SetRelativePath(v string) {
	o.RelativePath = &v
}

// GetMd5 returns the Md5 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetMd5() string {
	if o == nil || o.Md5 == nil {
		var ret string
		return ret
	}
	return *o.Md5
}

// GetMd5Ok returns a tuple with the Md5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetMd5Ok() (*string, bool) {
	if o == nil || o.Md5 == nil {
		return nil, false
	}
	return o.Md5, true
}

// HasMd5 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasMd5() bool {
	if o != nil && o.Md5 != nil {
		return true
	}

	return false
}

// SetMd5 gets a reference to the given string and assigns it to the Md5 field.
func (o *DebBasePackageResponse) SetMd5(v string) {
	o.Md5 = &v
}

// GetSha1 returns the Sha1 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSha1() string {
	if o == nil || o.Sha1 == nil {
		var ret string
		return ret
	}
	return *o.Sha1
}

// GetSha1Ok returns a tuple with the Sha1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSha1Ok() (*string, bool) {
	if o == nil || o.Sha1 == nil {
		return nil, false
	}
	return o.Sha1, true
}

// HasSha1 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSha1() bool {
	if o != nil && o.Sha1 != nil {
		return true
	}

	return false
}

// SetSha1 gets a reference to the given string and assigns it to the Sha1 field.
func (o *DebBasePackageResponse) SetSha1(v string) {
	o.Sha1 = &v
}

// GetSha224 returns the Sha224 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSha224() string {
	if o == nil || o.Sha224 == nil {
		var ret string
		return ret
	}
	return *o.Sha224
}

// GetSha224Ok returns a tuple with the Sha224 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSha224Ok() (*string, bool) {
	if o == nil || o.Sha224 == nil {
		return nil, false
	}
	return o.Sha224, true
}

// HasSha224 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSha224() bool {
	if o != nil && o.Sha224 != nil {
		return true
	}

	return false
}

// SetSha224 gets a reference to the given string and assigns it to the Sha224 field.
func (o *DebBasePackageResponse) SetSha224(v string) {
	o.Sha224 = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSha256() string {
	if o == nil || o.Sha256 == nil {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSha256Ok() (*string, bool) {
	if o == nil || o.Sha256 == nil {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSha256() bool {
	if o != nil && o.Sha256 != nil {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *DebBasePackageResponse) SetSha256(v string) {
	o.Sha256 = &v
}

// GetSha384 returns the Sha384 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSha384() string {
	if o == nil || o.Sha384 == nil {
		var ret string
		return ret
	}
	return *o.Sha384
}

// GetSha384Ok returns a tuple with the Sha384 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSha384Ok() (*string, bool) {
	if o == nil || o.Sha384 == nil {
		return nil, false
	}
	return o.Sha384, true
}

// HasSha384 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSha384() bool {
	if o != nil && o.Sha384 != nil {
		return true
	}

	return false
}

// SetSha384 gets a reference to the given string and assigns it to the Sha384 field.
func (o *DebBasePackageResponse) SetSha384(v string) {
	o.Sha384 = &v
}

// GetSha512 returns the Sha512 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSha512() string {
	if o == nil || o.Sha512 == nil {
		var ret string
		return ret
	}
	return *o.Sha512
}

// GetSha512Ok returns a tuple with the Sha512 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSha512Ok() (*string, bool) {
	if o == nil || o.Sha512 == nil {
		return nil, false
	}
	return o.Sha512, true
}

// HasSha512 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSha512() bool {
	if o != nil && o.Sha512 != nil {
		return true
	}

	return false
}

// SetSha512 gets a reference to the given string and assigns it to the Sha512 field.
func (o *DebBasePackageResponse) SetSha512(v string) {
	o.Sha512 = &v
}

// GetPackage returns the Package field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetPackage() string {
	if o == nil || o.Package == nil {
		var ret string
		return ret
	}
	return *o.Package
}

// GetPackageOk returns a tuple with the Package field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetPackageOk() (*string, bool) {
	if o == nil || o.Package == nil {
		return nil, false
	}
	return o.Package, true
}

// HasPackage returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasPackage() bool {
	if o != nil && o.Package != nil {
		return true
	}

	return false
}

// SetPackage gets a reference to the given string and assigns it to the Package field.
func (o *DebBasePackageResponse) SetPackage(v string) {
	o.Package = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *DebBasePackageResponse) SetSource(v string) {
	o.Source = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *DebBasePackageResponse) SetVersion(v string) {
	o.Version = &v
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetArchitecture() string {
	if o == nil || o.Architecture == nil {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetArchitectureOk() (*string, bool) {
	if o == nil || o.Architecture == nil {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasArchitecture() bool {
	if o != nil && o.Architecture != nil {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *DebBasePackageResponse) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetSection returns the Section field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSection() string {
	if o == nil || o.Section == nil {
		var ret string
		return ret
	}
	return *o.Section
}

// GetSectionOk returns a tuple with the Section field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSectionOk() (*string, bool) {
	if o == nil || o.Section == nil {
		return nil, false
	}
	return o.Section, true
}

// HasSection returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSection() bool {
	if o != nil && o.Section != nil {
		return true
	}

	return false
}

// SetSection gets a reference to the given string and assigns it to the Section field.
func (o *DebBasePackageResponse) SetSection(v string) {
	o.Section = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetPriority() string {
	if o == nil || o.Priority == nil {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetPriorityOk() (*string, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *DebBasePackageResponse) SetPriority(v string) {
	o.Priority = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetOrigin() string {
	if o == nil || o.Origin == nil {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetOriginOk() (*string, bool) {
	if o == nil || o.Origin == nil {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasOrigin() bool {
	if o != nil && o.Origin != nil {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *DebBasePackageResponse) SetOrigin(v string) {
	o.Origin = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetTag() string {
	if o == nil || o.Tag == nil {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetTagOk() (*string, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *DebBasePackageResponse) SetTag(v string) {
	o.Tag = &v
}

// GetBugs returns the Bugs field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetBugs() string {
	if o == nil || o.Bugs == nil {
		var ret string
		return ret
	}
	return *o.Bugs
}

// GetBugsOk returns a tuple with the Bugs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetBugsOk() (*string, bool) {
	if o == nil || o.Bugs == nil {
		return nil, false
	}
	return o.Bugs, true
}

// HasBugs returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasBugs() bool {
	if o != nil && o.Bugs != nil {
		return true
	}

	return false
}

// SetBugs gets a reference to the given string and assigns it to the Bugs field.
func (o *DebBasePackageResponse) SetBugs(v string) {
	o.Bugs = &v
}

// GetEssential returns the Essential field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetEssential() string {
	if o == nil || o.Essential == nil {
		var ret string
		return ret
	}
	return *o.Essential
}

// GetEssentialOk returns a tuple with the Essential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetEssentialOk() (*string, bool) {
	if o == nil || o.Essential == nil {
		return nil, false
	}
	return o.Essential, true
}

// HasEssential returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasEssential() bool {
	if o != nil && o.Essential != nil {
		return true
	}

	return false
}

// SetEssential gets a reference to the given string and assigns it to the Essential field.
func (o *DebBasePackageResponse) SetEssential(v string) {
	o.Essential = &v
}

// GetBuildEssential returns the BuildEssential field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetBuildEssential() string {
	if o == nil || o.BuildEssential == nil {
		var ret string
		return ret
	}
	return *o.BuildEssential
}

// GetBuildEssentialOk returns a tuple with the BuildEssential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetBuildEssentialOk() (*string, bool) {
	if o == nil || o.BuildEssential == nil {
		return nil, false
	}
	return o.BuildEssential, true
}

// HasBuildEssential returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasBuildEssential() bool {
	if o != nil && o.BuildEssential != nil {
		return true
	}

	return false
}

// SetBuildEssential gets a reference to the given string and assigns it to the BuildEssential field.
func (o *DebBasePackageResponse) SetBuildEssential(v string) {
	o.BuildEssential = &v
}

// GetInstalledSize returns the InstalledSize field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetInstalledSize() string {
	if o == nil || o.InstalledSize == nil {
		var ret string
		return ret
	}
	return *o.InstalledSize
}

// GetInstalledSizeOk returns a tuple with the InstalledSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetInstalledSizeOk() (*string, bool) {
	if o == nil || o.InstalledSize == nil {
		return nil, false
	}
	return o.InstalledSize, true
}

// HasInstalledSize returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasInstalledSize() bool {
	if o != nil && o.InstalledSize != nil {
		return true
	}

	return false
}

// SetInstalledSize gets a reference to the given string and assigns it to the InstalledSize field.
func (o *DebBasePackageResponse) SetInstalledSize(v string) {
	o.InstalledSize = &v
}

// GetMaintainer returns the Maintainer field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetMaintainer() string {
	if o == nil || o.Maintainer == nil {
		var ret string
		return ret
	}
	return *o.Maintainer
}

// GetMaintainerOk returns a tuple with the Maintainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetMaintainerOk() (*string, bool) {
	if o == nil || o.Maintainer == nil {
		return nil, false
	}
	return o.Maintainer, true
}

// HasMaintainer returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasMaintainer() bool {
	if o != nil && o.Maintainer != nil {
		return true
	}

	return false
}

// SetMaintainer gets a reference to the given string and assigns it to the Maintainer field.
func (o *DebBasePackageResponse) SetMaintainer(v string) {
	o.Maintainer = &v
}

// GetOriginalMaintainer returns the OriginalMaintainer field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetOriginalMaintainer() string {
	if o == nil || o.OriginalMaintainer == nil {
		var ret string
		return ret
	}
	return *o.OriginalMaintainer
}

// GetOriginalMaintainerOk returns a tuple with the OriginalMaintainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetOriginalMaintainerOk() (*string, bool) {
	if o == nil || o.OriginalMaintainer == nil {
		return nil, false
	}
	return o.OriginalMaintainer, true
}

// HasOriginalMaintainer returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasOriginalMaintainer() bool {
	if o != nil && o.OriginalMaintainer != nil {
		return true
	}

	return false
}

// SetOriginalMaintainer gets a reference to the given string and assigns it to the OriginalMaintainer field.
func (o *DebBasePackageResponse) SetOriginalMaintainer(v string) {
	o.OriginalMaintainer = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DebBasePackageResponse) SetDescription(v string) {
	o.Description = &v
}

// GetDescriptionMd5 returns the DescriptionMd5 field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetDescriptionMd5() string {
	if o == nil || o.DescriptionMd5 == nil {
		var ret string
		return ret
	}
	return *o.DescriptionMd5
}

// GetDescriptionMd5Ok returns a tuple with the DescriptionMd5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetDescriptionMd5Ok() (*string, bool) {
	if o == nil || o.DescriptionMd5 == nil {
		return nil, false
	}
	return o.DescriptionMd5, true
}

// HasDescriptionMd5 returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasDescriptionMd5() bool {
	if o != nil && o.DescriptionMd5 != nil {
		return true
	}

	return false
}

// SetDescriptionMd5 gets a reference to the given string and assigns it to the DescriptionMd5 field.
func (o *DebBasePackageResponse) SetDescriptionMd5(v string) {
	o.DescriptionMd5 = &v
}

// GetHomepage returns the Homepage field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetHomepage() string {
	if o == nil || o.Homepage == nil {
		var ret string
		return ret
	}
	return *o.Homepage
}

// GetHomepageOk returns a tuple with the Homepage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetHomepageOk() (*string, bool) {
	if o == nil || o.Homepage == nil {
		return nil, false
	}
	return o.Homepage, true
}

// HasHomepage returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasHomepage() bool {
	if o != nil && o.Homepage != nil {
		return true
	}

	return false
}

// SetHomepage gets a reference to the given string and assigns it to the Homepage field.
func (o *DebBasePackageResponse) SetHomepage(v string) {
	o.Homepage = &v
}

// GetBuiltUsing returns the BuiltUsing field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetBuiltUsing() string {
	if o == nil || o.BuiltUsing == nil {
		var ret string
		return ret
	}
	return *o.BuiltUsing
}

// GetBuiltUsingOk returns a tuple with the BuiltUsing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetBuiltUsingOk() (*string, bool) {
	if o == nil || o.BuiltUsing == nil {
		return nil, false
	}
	return o.BuiltUsing, true
}

// HasBuiltUsing returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasBuiltUsing() bool {
	if o != nil && o.BuiltUsing != nil {
		return true
	}

	return false
}

// SetBuiltUsing gets a reference to the given string and assigns it to the BuiltUsing field.
func (o *DebBasePackageResponse) SetBuiltUsing(v string) {
	o.BuiltUsing = &v
}

// GetAutoBuiltPackage returns the AutoBuiltPackage field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetAutoBuiltPackage() string {
	if o == nil || o.AutoBuiltPackage == nil {
		var ret string
		return ret
	}
	return *o.AutoBuiltPackage
}

// GetAutoBuiltPackageOk returns a tuple with the AutoBuiltPackage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetAutoBuiltPackageOk() (*string, bool) {
	if o == nil || o.AutoBuiltPackage == nil {
		return nil, false
	}
	return o.AutoBuiltPackage, true
}

// HasAutoBuiltPackage returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasAutoBuiltPackage() bool {
	if o != nil && o.AutoBuiltPackage != nil {
		return true
	}

	return false
}

// SetAutoBuiltPackage gets a reference to the given string and assigns it to the AutoBuiltPackage field.
func (o *DebBasePackageResponse) SetAutoBuiltPackage(v string) {
	o.AutoBuiltPackage = &v
}

// GetMultiArch returns the MultiArch field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetMultiArch() string {
	if o == nil || o.MultiArch == nil {
		var ret string
		return ret
	}
	return *o.MultiArch
}

// GetMultiArchOk returns a tuple with the MultiArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetMultiArchOk() (*string, bool) {
	if o == nil || o.MultiArch == nil {
		return nil, false
	}
	return o.MultiArch, true
}

// HasMultiArch returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasMultiArch() bool {
	if o != nil && o.MultiArch != nil {
		return true
	}

	return false
}

// SetMultiArch gets a reference to the given string and assigns it to the MultiArch field.
func (o *DebBasePackageResponse) SetMultiArch(v string) {
	o.MultiArch = &v
}

// GetBreaks returns the Breaks field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetBreaks() string {
	if o == nil || o.Breaks == nil {
		var ret string
		return ret
	}
	return *o.Breaks
}

// GetBreaksOk returns a tuple with the Breaks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetBreaksOk() (*string, bool) {
	if o == nil || o.Breaks == nil {
		return nil, false
	}
	return o.Breaks, true
}

// HasBreaks returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasBreaks() bool {
	if o != nil && o.Breaks != nil {
		return true
	}

	return false
}

// SetBreaks gets a reference to the given string and assigns it to the Breaks field.
func (o *DebBasePackageResponse) SetBreaks(v string) {
	o.Breaks = &v
}

// GetConflicts returns the Conflicts field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetConflicts() string {
	if o == nil || o.Conflicts == nil {
		var ret string
		return ret
	}
	return *o.Conflicts
}

// GetConflictsOk returns a tuple with the Conflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetConflictsOk() (*string, bool) {
	if o == nil || o.Conflicts == nil {
		return nil, false
	}
	return o.Conflicts, true
}

// HasConflicts returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasConflicts() bool {
	if o != nil && o.Conflicts != nil {
		return true
	}

	return false
}

// SetConflicts gets a reference to the given string and assigns it to the Conflicts field.
func (o *DebBasePackageResponse) SetConflicts(v string) {
	o.Conflicts = &v
}

// GetDepends returns the Depends field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetDepends() string {
	if o == nil || o.Depends == nil {
		var ret string
		return ret
	}
	return *o.Depends
}

// GetDependsOk returns a tuple with the Depends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetDependsOk() (*string, bool) {
	if o == nil || o.Depends == nil {
		return nil, false
	}
	return o.Depends, true
}

// HasDepends returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasDepends() bool {
	if o != nil && o.Depends != nil {
		return true
	}

	return false
}

// SetDepends gets a reference to the given string and assigns it to the Depends field.
func (o *DebBasePackageResponse) SetDepends(v string) {
	o.Depends = &v
}

// GetRecommends returns the Recommends field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetRecommends() string {
	if o == nil || o.Recommends == nil {
		var ret string
		return ret
	}
	return *o.Recommends
}

// GetRecommendsOk returns a tuple with the Recommends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetRecommendsOk() (*string, bool) {
	if o == nil || o.Recommends == nil {
		return nil, false
	}
	return o.Recommends, true
}

// HasRecommends returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasRecommends() bool {
	if o != nil && o.Recommends != nil {
		return true
	}

	return false
}

// SetRecommends gets a reference to the given string and assigns it to the Recommends field.
func (o *DebBasePackageResponse) SetRecommends(v string) {
	o.Recommends = &v
}

// GetSuggests returns the Suggests field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetSuggests() string {
	if o == nil || o.Suggests == nil {
		var ret string
		return ret
	}
	return *o.Suggests
}

// GetSuggestsOk returns a tuple with the Suggests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetSuggestsOk() (*string, bool) {
	if o == nil || o.Suggests == nil {
		return nil, false
	}
	return o.Suggests, true
}

// HasSuggests returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasSuggests() bool {
	if o != nil && o.Suggests != nil {
		return true
	}

	return false
}

// SetSuggests gets a reference to the given string and assigns it to the Suggests field.
func (o *DebBasePackageResponse) SetSuggests(v string) {
	o.Suggests = &v
}

// GetEnhances returns the Enhances field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetEnhances() string {
	if o == nil || o.Enhances == nil {
		var ret string
		return ret
	}
	return *o.Enhances
}

// GetEnhancesOk returns a tuple with the Enhances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetEnhancesOk() (*string, bool) {
	if o == nil || o.Enhances == nil {
		return nil, false
	}
	return o.Enhances, true
}

// HasEnhances returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasEnhances() bool {
	if o != nil && o.Enhances != nil {
		return true
	}

	return false
}

// SetEnhances gets a reference to the given string and assigns it to the Enhances field.
func (o *DebBasePackageResponse) SetEnhances(v string) {
	o.Enhances = &v
}

// GetPreDepends returns the PreDepends field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetPreDepends() string {
	if o == nil || o.PreDepends == nil {
		var ret string
		return ret
	}
	return *o.PreDepends
}

// GetPreDependsOk returns a tuple with the PreDepends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetPreDependsOk() (*string, bool) {
	if o == nil || o.PreDepends == nil {
		return nil, false
	}
	return o.PreDepends, true
}

// HasPreDepends returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasPreDepends() bool {
	if o != nil && o.PreDepends != nil {
		return true
	}

	return false
}

// SetPreDepends gets a reference to the given string and assigns it to the PreDepends field.
func (o *DebBasePackageResponse) SetPreDepends(v string) {
	o.PreDepends = &v
}

// GetProvides returns the Provides field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetProvides() string {
	if o == nil || o.Provides == nil {
		var ret string
		return ret
	}
	return *o.Provides
}

// GetProvidesOk returns a tuple with the Provides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetProvidesOk() (*string, bool) {
	if o == nil || o.Provides == nil {
		return nil, false
	}
	return o.Provides, true
}

// HasProvides returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasProvides() bool {
	if o != nil && o.Provides != nil {
		return true
	}

	return false
}

// SetProvides gets a reference to the given string and assigns it to the Provides field.
func (o *DebBasePackageResponse) SetProvides(v string) {
	o.Provides = &v
}

// GetReplaces returns the Replaces field value if set, zero value otherwise.
func (o *DebBasePackageResponse) GetReplaces() string {
	if o == nil || o.Replaces == nil {
		var ret string
		return ret
	}
	return *o.Replaces
}

// GetReplacesOk returns a tuple with the Replaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebBasePackageResponse) GetReplacesOk() (*string, bool) {
	if o == nil || o.Replaces == nil {
		return nil, false
	}
	return o.Replaces, true
}

// HasReplaces returns a boolean if a field has been set.
func (o *DebBasePackageResponse) HasReplaces() bool {
	if o != nil && o.Replaces != nil {
		return true
	}

	return false
}

// SetReplaces gets a reference to the given string and assigns it to the Replaces field.
func (o *DebBasePackageResponse) SetReplaces(v string) {
	o.Replaces = &v
}

func (o DebBasePackageResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PulpHref != nil {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if o.PulpCreated != nil {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if o.Artifact != nil {
		toSerialize["artifact"] = o.Artifact
	}
	if o.RelativePath != nil {
		toSerialize["relative_path"] = o.RelativePath
	}
	if o.Md5 != nil {
		toSerialize["md5"] = o.Md5
	}
	if o.Sha1 != nil {
		toSerialize["sha1"] = o.Sha1
	}
	if o.Sha224 != nil {
		toSerialize["sha224"] = o.Sha224
	}
	if o.Sha256 != nil {
		toSerialize["sha256"] = o.Sha256
	}
	if o.Sha384 != nil {
		toSerialize["sha384"] = o.Sha384
	}
	if o.Sha512 != nil {
		toSerialize["sha512"] = o.Sha512
	}
	if o.Package != nil {
		toSerialize["package"] = o.Package
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Architecture != nil {
		toSerialize["architecture"] = o.Architecture
	}
	if o.Section != nil {
		toSerialize["section"] = o.Section
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.Origin != nil {
		toSerialize["origin"] = o.Origin
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	if o.Bugs != nil {
		toSerialize["bugs"] = o.Bugs
	}
	if o.Essential != nil {
		toSerialize["essential"] = o.Essential
	}
	if o.BuildEssential != nil {
		toSerialize["build_essential"] = o.BuildEssential
	}
	if o.InstalledSize != nil {
		toSerialize["installed_size"] = o.InstalledSize
	}
	if o.Maintainer != nil {
		toSerialize["maintainer"] = o.Maintainer
	}
	if o.OriginalMaintainer != nil {
		toSerialize["original_maintainer"] = o.OriginalMaintainer
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DescriptionMd5 != nil {
		toSerialize["description_md5"] = o.DescriptionMd5
	}
	if o.Homepage != nil {
		toSerialize["homepage"] = o.Homepage
	}
	if o.BuiltUsing != nil {
		toSerialize["built_using"] = o.BuiltUsing
	}
	if o.AutoBuiltPackage != nil {
		toSerialize["auto_built_package"] = o.AutoBuiltPackage
	}
	if o.MultiArch != nil {
		toSerialize["multi_arch"] = o.MultiArch
	}
	if o.Breaks != nil {
		toSerialize["breaks"] = o.Breaks
	}
	if o.Conflicts != nil {
		toSerialize["conflicts"] = o.Conflicts
	}
	if o.Depends != nil {
		toSerialize["depends"] = o.Depends
	}
	if o.Recommends != nil {
		toSerialize["recommends"] = o.Recommends
	}
	if o.Suggests != nil {
		toSerialize["suggests"] = o.Suggests
	}
	if o.Enhances != nil {
		toSerialize["enhances"] = o.Enhances
	}
	if o.PreDepends != nil {
		toSerialize["pre_depends"] = o.PreDepends
	}
	if o.Provides != nil {
		toSerialize["provides"] = o.Provides
	}
	if o.Replaces != nil {
		toSerialize["replaces"] = o.Replaces
	}
	return json.Marshal(toSerialize)
}

type NullableDebBasePackageResponse struct {
	value *DebBasePackageResponse
	isSet bool
}

func (v NullableDebBasePackageResponse) Get() *DebBasePackageResponse {
	return v.value
}

func (v *NullableDebBasePackageResponse) Set(val *DebBasePackageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDebBasePackageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDebBasePackageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebBasePackageResponse(val *DebBasePackageResponse) *NullableDebBasePackageResponse {
	return &NullableDebBasePackageResponse{value: val, isSet: true}
}

func (v NullableDebBasePackageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebBasePackageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


